### ISSUE TITLE
Renderflex of the text inside the row widget .

### ISSUE THREAD

**Issue by ajibeshMohapatra** [viralvaghela/learnprogrammingfree#13]
![issue](https://user-images.githubusercontent.com/62394580/94984333-91747c00-0568-11eb-8fa8-3e47a5474cf7.jpeg)
Hello @viralvaghela you can just wrap the padding inside the row with an expanded widget to get it done . Also make the size of the python image smaller . And ya the search bar is not there it is there in my code . Would you resolve the issue or should I go for it ?

**Comment by viralvaghela** [comment]
Go for it @ajibeshMohapatra

**Comment by viralvaghela** [comment]
if the search bar is done then send PR, I will merge it.and then fix this overflow error

**Comment by ajibeshMohapatra** [comment]
The issue was resolved by the previous pull request i think .
