### ISSUE TITLE
add search bar in the flutter app

### ISSUE THREAD

**Issue by viralvaghela** [viralvaghela/learnprogrammingfree#5]

**Comment by arbazdiwan** [comment]
I will like to resolve issue #5.

If interested, please assign the task to me.

**Comment by ajibeshMohapatra** [comment]
hello @viralvaghela . Do you want the search bar to look into the tags only OR the tags and the instructor OR the tags , the instructor and the description also ? But in my opinion taking the description into consideration will be not good idea though . I can work it out and you can assign me .

**Comment by viralvaghela** [comment]
@ajibeshMohapatra  it's First Come First Serve so I am assigning this to @arbazdiwan
and  a search bar that searches for the tag and instructor
